version: '3'
    
services:
  hana-cockpit:
    image: entmike/hana-cockpit
    env_file: cockpit.env
    volumes:
      - /c/Users/RHOWLES/data/hana-cockpit/config:/app/config
    ports:
      - "8888:80"
          
  hxehost:
    image: store/saplabs/hanaexpress:2.00.036.00.20190223.1
    hostname: hxe
    ports:
      - 39017:39017
      - 39041:39041 
      - 39013:39013
      - 39015:39015
    volumes:
      - hxedev:/hana/mounts
    
volumes:
  hxedev:
    external:
      name: hxedev